"""init

Revision ID: 022cd1003fda
Revises: 
Create Date: 2025-09-09 00:50:50.290220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022cd1003fda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=300), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
